/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as OnboardingWhatsappRouteImport } from './routes/onboarding.whatsapp'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as AuthMetaCallbackRouteImport } from './routes/auth.meta.callback'
import { Route as ApiWhatsappTokenRefreshRouteImport } from './routes/api.whatsapp.token-refresh'
import { Route as ApiWhatsappTestSendRouteImport } from './routes/api.whatsapp.test-send'
import { Route as ApiWhatsappSendRouteImport } from './routes/api.whatsapp.send'
import { Route as ApiWhatsappIntegrationRouteImport } from './routes/api.whatsapp.integration'
import { Route as ApiWhatsappDebugRouteImport } from './routes/api.whatsapp.debug'
import { Route as ApiOnboardingMetaSaveRouteImport } from './routes/api.onboarding.meta-save'
import { Route as ApiMetaConfigRouteImport } from './routes/api.meta.config'
import { Route as ApiAiSuggestProductRouteImport } from './routes/api.ai.suggest-product'
import { Route as ApiAiSuggestRouteImport } from './routes/api.ai.suggest'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api.public.whatsapp.webhook'
import { Route as ApiPublicWhatsappQrIncomingRouteImport } from './routes/api.public.whatsapp-qr.incoming'

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const OnboardingWhatsappRoute = OnboardingWhatsappRouteImport.update({
  id: '/onboarding/whatsapp',
  path: '/onboarding/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => InboxRoute,
} as any)
const AuthMetaCallbackRoute = AuthMetaCallbackRouteImport.update({
  id: '/auth/meta/callback',
  path: '/auth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappTokenRefreshRoute = ApiWhatsappTokenRefreshRouteImport.update({
  id: '/api/whatsapp/token-refresh',
  path: '/api/whatsapp/token-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappTestSendRoute = ApiWhatsappTestSendRouteImport.update({
  id: '/api/whatsapp/test-send',
  path: '/api/whatsapp/test-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappSendRoute = ApiWhatsappSendRouteImport.update({
  id: '/api/whatsapp/send',
  path: '/api/whatsapp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappIntegrationRoute = ApiWhatsappIntegrationRouteImport.update({
  id: '/api/whatsapp/integration',
  path: '/api/whatsapp/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappDebugRoute = ApiWhatsappDebugRouteImport.update({
  id: '/api/whatsapp/debug',
  path: '/api/whatsapp/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingMetaSaveRoute = ApiOnboardingMetaSaveRouteImport.update({
  id: '/api/onboarding/meta-save',
  path: '/api/onboarding/meta-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaConfigRoute = ApiMetaConfigRouteImport.update({
  id: '/api/meta/config',
  path: '/api/meta/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSuggestProductRoute = ApiAiSuggestProductRouteImport.update({
  id: '/api/ai/suggest-product',
  path: '/api/ai/suggest-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSuggestRoute = ApiAiSuggestRouteImport.update({
  id: '/api/ai/suggest',
  path: '/api/ai/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappQrIncomingRoute =
  ApiPublicWhatsappQrIncomingRouteImport.update({
    id: '/api/public/whatsapp-qr/incoming',
    path: '/api/public/whatsapp-qr/incoming',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp': typeof WhatsappRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/inbox/': typeof InboxIndexRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/ai/suggest-product': typeof ApiAiSuggestProductRoute
  '/api/meta/config': typeof ApiMetaConfigRoute
  '/api/onboarding/meta-save': typeof ApiOnboardingMetaSaveRoute
  '/api/whatsapp/debug': typeof ApiWhatsappDebugRoute
  '/api/whatsapp/integration': typeof ApiWhatsappIntegrationRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/test-send': typeof ApiWhatsappTestSendRoute
  '/api/whatsapp/token-refresh': typeof ApiWhatsappTokenRefreshRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/public/whatsapp-qr/incoming': typeof ApiPublicWhatsappQrIncomingRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp': typeof WhatsappRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/inbox': typeof InboxIndexRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/ai/suggest-product': typeof ApiAiSuggestProductRoute
  '/api/meta/config': typeof ApiMetaConfigRoute
  '/api/onboarding/meta-save': typeof ApiOnboardingMetaSaveRoute
  '/api/whatsapp/debug': typeof ApiWhatsappDebugRoute
  '/api/whatsapp/integration': typeof ApiWhatsappIntegrationRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/test-send': typeof ApiWhatsappTestSendRoute
  '/api/whatsapp/token-refresh': typeof ApiWhatsappTokenRefreshRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/public/whatsapp-qr/incoming': typeof ApiPublicWhatsappQrIncomingRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/whatsapp': typeof WhatsappRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/inbox/': typeof InboxIndexRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/ai/suggest-product': typeof ApiAiSuggestProductRoute
  '/api/meta/config': typeof ApiMetaConfigRoute
  '/api/onboarding/meta-save': typeof ApiOnboardingMetaSaveRoute
  '/api/whatsapp/debug': typeof ApiWhatsappDebugRoute
  '/api/whatsapp/integration': typeof ApiWhatsappIntegrationRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/test-send': typeof ApiWhatsappTestSendRoute
  '/api/whatsapp/token-refresh': typeof ApiWhatsappTokenRefreshRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/public/whatsapp-qr/incoming': typeof ApiPublicWhatsappQrIncomingRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/inbox'
    | '/login'
    | '/orcamentos'
    | '/privacidade'
    | '/privacy'
    | '/produtos'
    | '/relatorios'
    | '/reset-password'
    | '/whatsapp'
    | '/inbox/$conversationId'
    | '/onboarding/whatsapp'
    | '/inbox/'
    | '/api/ai/suggest'
    | '/api/ai/suggest-product'
    | '/api/meta/config'
    | '/api/onboarding/meta-save'
    | '/api/whatsapp/debug'
    | '/api/whatsapp/integration'
    | '/api/whatsapp/send'
    | '/api/whatsapp/test-send'
    | '/api/whatsapp/token-refresh'
    | '/auth/meta/callback'
    | '/api/public/whatsapp-qr/incoming'
    | '/api/public/whatsapp/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/login'
    | '/orcamentos'
    | '/privacidade'
    | '/privacy'
    | '/produtos'
    | '/relatorios'
    | '/reset-password'
    | '/whatsapp'
    | '/inbox/$conversationId'
    | '/onboarding/whatsapp'
    | '/inbox'
    | '/api/ai/suggest'
    | '/api/ai/suggest-product'
    | '/api/meta/config'
    | '/api/onboarding/meta-save'
    | '/api/whatsapp/debug'
    | '/api/whatsapp/integration'
    | '/api/whatsapp/send'
    | '/api/whatsapp/test-send'
    | '/api/whatsapp/token-refresh'
    | '/auth/meta/callback'
    | '/api/public/whatsapp-qr/incoming'
    | '/api/public/whatsapp/webhook'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/inbox'
    | '/login'
    | '/orcamentos'
    | '/privacidade'
    | '/privacy'
    | '/produtos'
    | '/relatorios'
    | '/reset-password'
    | '/whatsapp'
    | '/inbox/$conversationId'
    | '/onboarding/whatsapp'
    | '/inbox/'
    | '/api/ai/suggest'
    | '/api/ai/suggest-product'
    | '/api/meta/config'
    | '/api/onboarding/meta-save'
    | '/api/whatsapp/debug'
    | '/api/whatsapp/integration'
    | '/api/whatsapp/send'
    | '/api/whatsapp/test-send'
    | '/api/whatsapp/token-refresh'
    | '/auth/meta/callback'
    | '/api/public/whatsapp-qr/incoming'
    | '/api/public/whatsapp/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  InboxRoute: typeof InboxRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  WhatsappRoute: typeof WhatsappRoute
  OnboardingWhatsappRoute: typeof OnboardingWhatsappRoute
  ApiAiSuggestRoute: typeof ApiAiSuggestRoute
  ApiAiSuggestProductRoute: typeof ApiAiSuggestProductRoute
  ApiMetaConfigRoute: typeof ApiMetaConfigRoute
  ApiOnboardingMetaSaveRoute: typeof ApiOnboardingMetaSaveRoute
  ApiWhatsappDebugRoute: typeof ApiWhatsappDebugRoute
  ApiWhatsappIntegrationRoute: typeof ApiWhatsappIntegrationRoute
  ApiWhatsappSendRoute: typeof ApiWhatsappSendRoute
  ApiWhatsappTestSendRoute: typeof ApiWhatsappTestSendRoute
  ApiWhatsappTokenRefreshRoute: typeof ApiWhatsappTokenRefreshRoute
  AuthMetaCallbackRoute: typeof AuthMetaCallbackRoute
  ApiPublicWhatsappQrIncomingRoute: typeof ApiPublicWhatsappQrIncomingRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/onboarding/whatsapp': {
      id: '/onboarding/whatsapp'
      path: '/onboarding/whatsapp'
      fullPath: '/onboarding/whatsapp'
      preLoaderRoute: typeof OnboardingWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/auth/meta/callback': {
      id: '/auth/meta/callback'
      path: '/auth/meta/callback'
      fullPath: '/auth/meta/callback'
      preLoaderRoute: typeof AuthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/token-refresh': {
      id: '/api/whatsapp/token-refresh'
      path: '/api/whatsapp/token-refresh'
      fullPath: '/api/whatsapp/token-refresh'
      preLoaderRoute: typeof ApiWhatsappTokenRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/test-send': {
      id: '/api/whatsapp/test-send'
      path: '/api/whatsapp/test-send'
      fullPath: '/api/whatsapp/test-send'
      preLoaderRoute: typeof ApiWhatsappTestSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/send': {
      id: '/api/whatsapp/send'
      path: '/api/whatsapp/send'
      fullPath: '/api/whatsapp/send'
      preLoaderRoute: typeof ApiWhatsappSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/integration': {
      id: '/api/whatsapp/integration'
      path: '/api/whatsapp/integration'
      fullPath: '/api/whatsapp/integration'
      preLoaderRoute: typeof ApiWhatsappIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/debug': {
      id: '/api/whatsapp/debug'
      path: '/api/whatsapp/debug'
      fullPath: '/api/whatsapp/debug'
      preLoaderRoute: typeof ApiWhatsappDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/meta-save': {
      id: '/api/onboarding/meta-save'
      path: '/api/onboarding/meta-save'
      fullPath: '/api/onboarding/meta-save'
      preLoaderRoute: typeof ApiOnboardingMetaSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/config': {
      id: '/api/meta/config'
      path: '/api/meta/config'
      fullPath: '/api/meta/config'
      preLoaderRoute: typeof ApiMetaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/suggest-product': {
      id: '/api/ai/suggest-product'
      path: '/api/ai/suggest-product'
      fullPath: '/api/ai/suggest-product'
      preLoaderRoute: typeof ApiAiSuggestProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/suggest': {
      id: '/api/ai/suggest'
      path: '/api/ai/suggest'
      fullPath: '/api/ai/suggest'
      preLoaderRoute: typeof ApiAiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp-qr/incoming': {
      id: '/api/public/whatsapp-qr/incoming'
      path: '/api/public/whatsapp-qr/incoming'
      fullPath: '/api/public/whatsapp-qr/incoming'
      preLoaderRoute: typeof ApiPublicWhatsappQrIncomingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxConversationIdRoute: typeof InboxConversationIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxConversationIdRoute: InboxConversationIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  InboxRoute: InboxRouteWithChildren,
  LoginRoute: LoginRoute,
  OrcamentosRoute: OrcamentosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PrivacyRoute: PrivacyRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  WhatsappRoute: WhatsappRoute,
  OnboardingWhatsappRoute: OnboardingWhatsappRoute,
  ApiAiSuggestRoute: ApiAiSuggestRoute,
  ApiAiSuggestProductRoute: ApiAiSuggestProductRoute,
  ApiMetaConfigRoute: ApiMetaConfigRoute,
  ApiOnboardingMetaSaveRoute: ApiOnboardingMetaSaveRoute,
  ApiWhatsappDebugRoute: ApiWhatsappDebugRoute,
  ApiWhatsappIntegrationRoute: ApiWhatsappIntegrationRoute,
  ApiWhatsappSendRoute: ApiWhatsappSendRoute,
  ApiWhatsappTestSendRoute: ApiWhatsappTestSendRoute,
  ApiWhatsappTokenRefreshRoute: ApiWhatsappTokenRefreshRoute,
  AuthMetaCallbackRoute: AuthMetaCallbackRoute,
  ApiPublicWhatsappQrIncomingRoute: ApiPublicWhatsappQrIncomingRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
