/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhatsappRouteImport } from './routes/whatsapp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OrcamentosRouteImport } from './routes/orcamentos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IaRouteImport } from './routes/ia'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InboxIndexRouteImport } from './routes/inbox.index'
import { Route as OnboardingWhatsappRouteImport } from './routes/onboarding.whatsapp'
import { Route as InboxConversationIdRouteImport } from './routes/inbox.$conversationId'
import { Route as AuthMetaCallbackRouteImport } from './routes/auth.meta.callback'
import { Route as ApiWhatsappUnmappedRouteImport } from './routes/api.whatsapp.unmapped'
import { Route as ApiWhatsappTokenRefreshRouteImport } from './routes/api.whatsapp.token-refresh'
import { Route as ApiWhatsappTestSendRouteImport } from './routes/api.whatsapp.test-send'
import { Route as ApiWhatsappSendRouteImport } from './routes/api.whatsapp.send'
import { Route as ApiWhatsappIntegrationRouteImport } from './routes/api.whatsapp.integration'
import { Route as ApiWhatsappDebugRouteImport } from './routes/api.whatsapp.debug'
import { Route as ApiOnboardingTestSendRouteImport } from './routes/api.onboarding.test-send'
import { Route as ApiOnboardingMetaSaveRouteImport } from './routes/api.onboarding.meta-save'
import { Route as ApiMetaConfigRouteImport } from './routes/api.meta.config'
import { Route as ApiAiTestNowRouteImport } from './routes/api.ai.test-now'
import { Route as ApiAiSuggestProductRouteImport } from './routes/api.ai.suggest-product'
import { Route as ApiAiSuggestRouteImport } from './routes/api.ai.suggest'
import { Route as ApiAiReadinessRouteImport } from './routes/api.ai.readiness'
import { Route as ApiAiProposeKnowledgeRouteImport } from './routes/api.ai.propose-knowledge'
import { Route as ApiAiPilotToggleRouteImport } from './routes/api.ai.pilot-toggle'
import { Route as ApiAiMarkSentRouteImport } from './routes/api.ai.mark-sent'
import { Route as ApiAiFollowupStatusRouteImport } from './routes/api.ai.followup-status'
import { Route as ApiAiFollowupReactivateRouteImport } from './routes/api.ai.followup-reactivate'
import { Route as ApiAiFollowupConfigRouteImport } from './routes/api.ai.followup-config'
import { Route as ApiAiAnalyticsRouteImport } from './routes/api.ai.analytics'
import { Route as ApiAiAgentTickRouteImport } from './routes/api.ai.agent-tick'
import { Route as ApiAiAgentTakeoverRouteImport } from './routes/api.ai.agent-takeover'
import { Route as ApiWhatsappTemplatesUpdateRouteImport } from './routes/api.whatsapp.templates.update'
import { Route as ApiWhatsappTemplatesSyncRouteImport } from './routes/api.whatsapp.templates.sync'
import { Route as ApiWhatsappTemplatesListRouteImport } from './routes/api.whatsapp.templates.list'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api.public.whatsapp.webhook'
import { Route as ApiPublicHooksFollowupTickRouteImport } from './routes/api.public.hooks.followup-tick'
import { Route as ApiPublicHooksAgentTriggerRouteImport } from './routes/api.public.hooks.agent-trigger'

const CampanhasIndexLazyRouteImport = createFileRoute('/campanhas/')()
const CampanhasNovaLazyRouteImport = createFileRoute('/campanhas/nova')()
const CampanhasIdLazyRouteImport = createFileRoute('/campanhas/$id')()

const WhatsappRoute = WhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OrcamentosRoute = OrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IaRoute = IaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampanhasIndexLazyRoute = CampanhasIndexLazyRouteImport.update({
  id: '/campanhas/',
  path: '/campanhas/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/campanhas.index.lazy').then((d) => d.Route),
)
const InboxIndexRoute = InboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InboxRoute,
} as any)
const CampanhasNovaLazyRoute = CampanhasNovaLazyRouteImport.update({
  id: '/campanhas/nova',
  path: '/campanhas/nova',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/campanhas.nova.lazy').then((d) => d.Route),
)
const CampanhasIdLazyRoute = CampanhasIdLazyRouteImport.update({
  id: '/campanhas/$id',
  path: '/campanhas/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/campanhas.$id.lazy').then((d) => d.Route))
const OnboardingWhatsappRoute = OnboardingWhatsappRouteImport.update({
  id: '/onboarding/whatsapp',
  path: '/onboarding/whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxConversationIdRoute = InboxConversationIdRouteImport.update({
  id: '/$conversationId',
  path: '/$conversationId',
  getParentRoute: () => InboxRoute,
} as any)
const AuthMetaCallbackRoute = AuthMetaCallbackRouteImport.update({
  id: '/auth/meta/callback',
  path: '/auth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappUnmappedRoute = ApiWhatsappUnmappedRouteImport.update({
  id: '/api/whatsapp/unmapped',
  path: '/api/whatsapp/unmapped',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappTokenRefreshRoute = ApiWhatsappTokenRefreshRouteImport.update({
  id: '/api/whatsapp/token-refresh',
  path: '/api/whatsapp/token-refresh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappTestSendRoute = ApiWhatsappTestSendRouteImport.update({
  id: '/api/whatsapp/test-send',
  path: '/api/whatsapp/test-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappSendRoute = ApiWhatsappSendRouteImport.update({
  id: '/api/whatsapp/send',
  path: '/api/whatsapp/send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappIntegrationRoute = ApiWhatsappIntegrationRouteImport.update({
  id: '/api/whatsapp/integration',
  path: '/api/whatsapp/integration',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappDebugRoute = ApiWhatsappDebugRouteImport.update({
  id: '/api/whatsapp/debug',
  path: '/api/whatsapp/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingTestSendRoute = ApiOnboardingTestSendRouteImport.update({
  id: '/api/onboarding/test-send',
  path: '/api/onboarding/test-send',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOnboardingMetaSaveRoute = ApiOnboardingMetaSaveRouteImport.update({
  id: '/api/onboarding/meta-save',
  path: '/api/onboarding/meta-save',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetaConfigRoute = ApiMetaConfigRouteImport.update({
  id: '/api/meta/config',
  path: '/api/meta/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiTestNowRoute = ApiAiTestNowRouteImport.update({
  id: '/api/ai/test-now',
  path: '/api/ai/test-now',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSuggestProductRoute = ApiAiSuggestProductRouteImport.update({
  id: '/api/ai/suggest-product',
  path: '/api/ai/suggest-product',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiSuggestRoute = ApiAiSuggestRouteImport.update({
  id: '/api/ai/suggest',
  path: '/api/ai/suggest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiReadinessRoute = ApiAiReadinessRouteImport.update({
  id: '/api/ai/readiness',
  path: '/api/ai/readiness',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiProposeKnowledgeRoute = ApiAiProposeKnowledgeRouteImport.update({
  id: '/api/ai/propose-knowledge',
  path: '/api/ai/propose-knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiPilotToggleRoute = ApiAiPilotToggleRouteImport.update({
  id: '/api/ai/pilot-toggle',
  path: '/api/ai/pilot-toggle',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiMarkSentRoute = ApiAiMarkSentRouteImport.update({
  id: '/api/ai/mark-sent',
  path: '/api/ai/mark-sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFollowupStatusRoute = ApiAiFollowupStatusRouteImport.update({
  id: '/api/ai/followup-status',
  path: '/api/ai/followup-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFollowupReactivateRoute = ApiAiFollowupReactivateRouteImport.update({
  id: '/api/ai/followup-reactivate',
  path: '/api/ai/followup-reactivate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiFollowupConfigRoute = ApiAiFollowupConfigRouteImport.update({
  id: '/api/ai/followup-config',
  path: '/api/ai/followup-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAnalyticsRoute = ApiAiAnalyticsRouteImport.update({
  id: '/api/ai/analytics',
  path: '/api/ai/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAgentTickRoute = ApiAiAgentTickRouteImport.update({
  id: '/api/ai/agent-tick',
  path: '/api/ai/agent-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiAgentTakeoverRoute = ApiAiAgentTakeoverRouteImport.update({
  id: '/api/ai/agent-takeover',
  path: '/api/ai/agent-takeover',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWhatsappTemplatesUpdateRoute =
  ApiWhatsappTemplatesUpdateRouteImport.update({
    id: '/api/whatsapp/templates/update',
    path: '/api/whatsapp/templates/update',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWhatsappTemplatesSyncRoute =
  ApiWhatsappTemplatesSyncRouteImport.update({
    id: '/api/whatsapp/templates/sync',
    path: '/api/whatsapp/templates/sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiWhatsappTemplatesListRoute =
  ApiWhatsappTemplatesListRouteImport.update({
    id: '/api/whatsapp/templates/list',
    path: '/api/whatsapp/templates/list',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFollowupTickRoute =
  ApiPublicHooksFollowupTickRouteImport.update({
    id: '/api/public/hooks/followup-tick',
    path: '/api/public/hooks/followup-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentTriggerRoute =
  ApiPublicHooksAgentTriggerRouteImport.update({
    id: '/api/public/hooks/agent-trigger',
    path: '/api/public/hooks/agent-trigger',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ia': typeof IaRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/whatsapp': typeof WhatsappRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/campanhas/$id': typeof CampanhasIdLazyRoute
  '/campanhas/nova': typeof CampanhasNovaLazyRoute
  '/inbox/': typeof InboxIndexRoute
  '/campanhas/': typeof CampanhasIndexLazyRoute
  '/api/ai/agent-takeover': typeof ApiAiAgentTakeoverRoute
  '/api/ai/agent-tick': typeof ApiAiAgentTickRoute
  '/api/ai/analytics': typeof ApiAiAnalyticsRoute
  '/api/ai/followup-config': typeof ApiAiFollowupConfigRoute
  '/api/ai/followup-reactivate': typeof ApiAiFollowupReactivateRoute
  '/api/ai/followup-status': typeof ApiAiFollowupStatusRoute
  '/api/ai/mark-sent': typeof ApiAiMarkSentRoute
  '/api/ai/pilot-toggle': typeof ApiAiPilotToggleRoute
  '/api/ai/propose-knowledge': typeof ApiAiProposeKnowledgeRoute
  '/api/ai/readiness': typeof ApiAiReadinessRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/ai/suggest-product': typeof ApiAiSuggestProductRoute
  '/api/ai/test-now': typeof ApiAiTestNowRoute
  '/api/meta/config': typeof ApiMetaConfigRoute
  '/api/onboarding/meta-save': typeof ApiOnboardingMetaSaveRoute
  '/api/onboarding/test-send': typeof ApiOnboardingTestSendRoute
  '/api/whatsapp/debug': typeof ApiWhatsappDebugRoute
  '/api/whatsapp/integration': typeof ApiWhatsappIntegrationRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/test-send': typeof ApiWhatsappTestSendRoute
  '/api/whatsapp/token-refresh': typeof ApiWhatsappTokenRefreshRoute
  '/api/whatsapp/unmapped': typeof ApiWhatsappUnmappedRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/public/hooks/agent-trigger': typeof ApiPublicHooksAgentTriggerRoute
  '/api/public/hooks/followup-tick': typeof ApiPublicHooksFollowupTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/whatsapp/templates/list': typeof ApiWhatsappTemplatesListRoute
  '/api/whatsapp/templates/sync': typeof ApiWhatsappTemplatesSyncRoute
  '/api/whatsapp/templates/update': typeof ApiWhatsappTemplatesUpdateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ia': typeof IaRoute
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/whatsapp': typeof WhatsappRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/campanhas/$id': typeof CampanhasIdLazyRoute
  '/campanhas/nova': typeof CampanhasNovaLazyRoute
  '/inbox': typeof InboxIndexRoute
  '/campanhas': typeof CampanhasIndexLazyRoute
  '/api/ai/agent-takeover': typeof ApiAiAgentTakeoverRoute
  '/api/ai/agent-tick': typeof ApiAiAgentTickRoute
  '/api/ai/analytics': typeof ApiAiAnalyticsRoute
  '/api/ai/followup-config': typeof ApiAiFollowupConfigRoute
  '/api/ai/followup-reactivate': typeof ApiAiFollowupReactivateRoute
  '/api/ai/followup-status': typeof ApiAiFollowupStatusRoute
  '/api/ai/mark-sent': typeof ApiAiMarkSentRoute
  '/api/ai/pilot-toggle': typeof ApiAiPilotToggleRoute
  '/api/ai/propose-knowledge': typeof ApiAiProposeKnowledgeRoute
  '/api/ai/readiness': typeof ApiAiReadinessRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/ai/suggest-product': typeof ApiAiSuggestProductRoute
  '/api/ai/test-now': typeof ApiAiTestNowRoute
  '/api/meta/config': typeof ApiMetaConfigRoute
  '/api/onboarding/meta-save': typeof ApiOnboardingMetaSaveRoute
  '/api/onboarding/test-send': typeof ApiOnboardingTestSendRoute
  '/api/whatsapp/debug': typeof ApiWhatsappDebugRoute
  '/api/whatsapp/integration': typeof ApiWhatsappIntegrationRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/test-send': typeof ApiWhatsappTestSendRoute
  '/api/whatsapp/token-refresh': typeof ApiWhatsappTokenRefreshRoute
  '/api/whatsapp/unmapped': typeof ApiWhatsappUnmappedRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/public/hooks/agent-trigger': typeof ApiPublicHooksAgentTriggerRoute
  '/api/public/hooks/followup-tick': typeof ApiPublicHooksFollowupTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/whatsapp/templates/list': typeof ApiWhatsappTemplatesListRoute
  '/api/whatsapp/templates/sync': typeof ApiWhatsappTemplatesSyncRoute
  '/api/whatsapp/templates/update': typeof ApiWhatsappTemplatesUpdateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/ia': typeof IaRoute
  '/inbox': typeof InboxRouteWithChildren
  '/login': typeof LoginRoute
  '/orcamentos': typeof OrcamentosRoute
  '/privacidade': typeof PrivacidadeRoute
  '/privacy': typeof PrivacyRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/whatsapp': typeof WhatsappRoute
  '/inbox/$conversationId': typeof InboxConversationIdRoute
  '/onboarding/whatsapp': typeof OnboardingWhatsappRoute
  '/campanhas/$id': typeof CampanhasIdLazyRoute
  '/campanhas/nova': typeof CampanhasNovaLazyRoute
  '/inbox/': typeof InboxIndexRoute
  '/campanhas/': typeof CampanhasIndexLazyRoute
  '/api/ai/agent-takeover': typeof ApiAiAgentTakeoverRoute
  '/api/ai/agent-tick': typeof ApiAiAgentTickRoute
  '/api/ai/analytics': typeof ApiAiAnalyticsRoute
  '/api/ai/followup-config': typeof ApiAiFollowupConfigRoute
  '/api/ai/followup-reactivate': typeof ApiAiFollowupReactivateRoute
  '/api/ai/followup-status': typeof ApiAiFollowupStatusRoute
  '/api/ai/mark-sent': typeof ApiAiMarkSentRoute
  '/api/ai/pilot-toggle': typeof ApiAiPilotToggleRoute
  '/api/ai/propose-knowledge': typeof ApiAiProposeKnowledgeRoute
  '/api/ai/readiness': typeof ApiAiReadinessRoute
  '/api/ai/suggest': typeof ApiAiSuggestRoute
  '/api/ai/suggest-product': typeof ApiAiSuggestProductRoute
  '/api/ai/test-now': typeof ApiAiTestNowRoute
  '/api/meta/config': typeof ApiMetaConfigRoute
  '/api/onboarding/meta-save': typeof ApiOnboardingMetaSaveRoute
  '/api/onboarding/test-send': typeof ApiOnboardingTestSendRoute
  '/api/whatsapp/debug': typeof ApiWhatsappDebugRoute
  '/api/whatsapp/integration': typeof ApiWhatsappIntegrationRoute
  '/api/whatsapp/send': typeof ApiWhatsappSendRoute
  '/api/whatsapp/test-send': typeof ApiWhatsappTestSendRoute
  '/api/whatsapp/token-refresh': typeof ApiWhatsappTokenRefreshRoute
  '/api/whatsapp/unmapped': typeof ApiWhatsappUnmappedRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/api/public/hooks/agent-trigger': typeof ApiPublicHooksAgentTriggerRoute
  '/api/public/hooks/followup-tick': typeof ApiPublicHooksFollowupTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/api/whatsapp/templates/list': typeof ApiWhatsappTemplatesListRoute
  '/api/whatsapp/templates/sync': typeof ApiWhatsappTemplatesSyncRoute
  '/api/whatsapp/templates/update': typeof ApiWhatsappTemplatesUpdateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/ia'
    | '/inbox'
    | '/login'
    | '/orcamentos'
    | '/privacidade'
    | '/privacy'
    | '/produtos'
    | '/relatorios'
    | '/reset-password'
    | '/sitemap.xml'
    | '/whatsapp'
    | '/inbox/$conversationId'
    | '/onboarding/whatsapp'
    | '/campanhas/$id'
    | '/campanhas/nova'
    | '/inbox/'
    | '/campanhas/'
    | '/api/ai/agent-takeover'
    | '/api/ai/agent-tick'
    | '/api/ai/analytics'
    | '/api/ai/followup-config'
    | '/api/ai/followup-reactivate'
    | '/api/ai/followup-status'
    | '/api/ai/mark-sent'
    | '/api/ai/pilot-toggle'
    | '/api/ai/propose-knowledge'
    | '/api/ai/readiness'
    | '/api/ai/suggest'
    | '/api/ai/suggest-product'
    | '/api/ai/test-now'
    | '/api/meta/config'
    | '/api/onboarding/meta-save'
    | '/api/onboarding/test-send'
    | '/api/whatsapp/debug'
    | '/api/whatsapp/integration'
    | '/api/whatsapp/send'
    | '/api/whatsapp/test-send'
    | '/api/whatsapp/token-refresh'
    | '/api/whatsapp/unmapped'
    | '/auth/meta/callback'
    | '/api/public/hooks/agent-trigger'
    | '/api/public/hooks/followup-tick'
    | '/api/public/whatsapp/webhook'
    | '/api/whatsapp/templates/list'
    | '/api/whatsapp/templates/sync'
    | '/api/whatsapp/templates/update'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/ia'
    | '/login'
    | '/orcamentos'
    | '/privacidade'
    | '/privacy'
    | '/produtos'
    | '/relatorios'
    | '/reset-password'
    | '/sitemap.xml'
    | '/whatsapp'
    | '/inbox/$conversationId'
    | '/onboarding/whatsapp'
    | '/campanhas/$id'
    | '/campanhas/nova'
    | '/inbox'
    | '/campanhas'
    | '/api/ai/agent-takeover'
    | '/api/ai/agent-tick'
    | '/api/ai/analytics'
    | '/api/ai/followup-config'
    | '/api/ai/followup-reactivate'
    | '/api/ai/followup-status'
    | '/api/ai/mark-sent'
    | '/api/ai/pilot-toggle'
    | '/api/ai/propose-knowledge'
    | '/api/ai/readiness'
    | '/api/ai/suggest'
    | '/api/ai/suggest-product'
    | '/api/ai/test-now'
    | '/api/meta/config'
    | '/api/onboarding/meta-save'
    | '/api/onboarding/test-send'
    | '/api/whatsapp/debug'
    | '/api/whatsapp/integration'
    | '/api/whatsapp/send'
    | '/api/whatsapp/test-send'
    | '/api/whatsapp/token-refresh'
    | '/api/whatsapp/unmapped'
    | '/auth/meta/callback'
    | '/api/public/hooks/agent-trigger'
    | '/api/public/hooks/followup-tick'
    | '/api/public/whatsapp/webhook'
    | '/api/whatsapp/templates/list'
    | '/api/whatsapp/templates/sync'
    | '/api/whatsapp/templates/update'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/ia'
    | '/inbox'
    | '/login'
    | '/orcamentos'
    | '/privacidade'
    | '/privacy'
    | '/produtos'
    | '/relatorios'
    | '/reset-password'
    | '/sitemap.xml'
    | '/whatsapp'
    | '/inbox/$conversationId'
    | '/onboarding/whatsapp'
    | '/campanhas/$id'
    | '/campanhas/nova'
    | '/inbox/'
    | '/campanhas/'
    | '/api/ai/agent-takeover'
    | '/api/ai/agent-tick'
    | '/api/ai/analytics'
    | '/api/ai/followup-config'
    | '/api/ai/followup-reactivate'
    | '/api/ai/followup-status'
    | '/api/ai/mark-sent'
    | '/api/ai/pilot-toggle'
    | '/api/ai/propose-knowledge'
    | '/api/ai/readiness'
    | '/api/ai/suggest'
    | '/api/ai/suggest-product'
    | '/api/ai/test-now'
    | '/api/meta/config'
    | '/api/onboarding/meta-save'
    | '/api/onboarding/test-send'
    | '/api/whatsapp/debug'
    | '/api/whatsapp/integration'
    | '/api/whatsapp/send'
    | '/api/whatsapp/test-send'
    | '/api/whatsapp/token-refresh'
    | '/api/whatsapp/unmapped'
    | '/auth/meta/callback'
    | '/api/public/hooks/agent-trigger'
    | '/api/public/hooks/followup-tick'
    | '/api/public/whatsapp/webhook'
    | '/api/whatsapp/templates/list'
    | '/api/whatsapp/templates/sync'
    | '/api/whatsapp/templates/update'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  IaRoute: typeof IaRoute
  InboxRoute: typeof InboxRouteWithChildren
  LoginRoute: typeof LoginRoute
  OrcamentosRoute: typeof OrcamentosRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  PrivacyRoute: typeof PrivacyRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WhatsappRoute: typeof WhatsappRoute
  OnboardingWhatsappRoute: typeof OnboardingWhatsappRoute
  CampanhasIdLazyRoute: typeof CampanhasIdLazyRoute
  CampanhasNovaLazyRoute: typeof CampanhasNovaLazyRoute
  CampanhasIndexLazyRoute: typeof CampanhasIndexLazyRoute
  ApiAiAgentTakeoverRoute: typeof ApiAiAgentTakeoverRoute
  ApiAiAgentTickRoute: typeof ApiAiAgentTickRoute
  ApiAiAnalyticsRoute: typeof ApiAiAnalyticsRoute
  ApiAiFollowupConfigRoute: typeof ApiAiFollowupConfigRoute
  ApiAiFollowupReactivateRoute: typeof ApiAiFollowupReactivateRoute
  ApiAiFollowupStatusRoute: typeof ApiAiFollowupStatusRoute
  ApiAiMarkSentRoute: typeof ApiAiMarkSentRoute
  ApiAiPilotToggleRoute: typeof ApiAiPilotToggleRoute
  ApiAiProposeKnowledgeRoute: typeof ApiAiProposeKnowledgeRoute
  ApiAiReadinessRoute: typeof ApiAiReadinessRoute
  ApiAiSuggestRoute: typeof ApiAiSuggestRoute
  ApiAiSuggestProductRoute: typeof ApiAiSuggestProductRoute
  ApiAiTestNowRoute: typeof ApiAiTestNowRoute
  ApiMetaConfigRoute: typeof ApiMetaConfigRoute
  ApiOnboardingMetaSaveRoute: typeof ApiOnboardingMetaSaveRoute
  ApiOnboardingTestSendRoute: typeof ApiOnboardingTestSendRoute
  ApiWhatsappDebugRoute: typeof ApiWhatsappDebugRoute
  ApiWhatsappIntegrationRoute: typeof ApiWhatsappIntegrationRoute
  ApiWhatsappSendRoute: typeof ApiWhatsappSendRoute
  ApiWhatsappTestSendRoute: typeof ApiWhatsappTestSendRoute
  ApiWhatsappTokenRefreshRoute: typeof ApiWhatsappTokenRefreshRoute
  ApiWhatsappUnmappedRoute: typeof ApiWhatsappUnmappedRoute
  AuthMetaCallbackRoute: typeof AuthMetaCallbackRoute
  ApiPublicHooksAgentTriggerRoute: typeof ApiPublicHooksAgentTriggerRoute
  ApiPublicHooksFollowupTickRoute: typeof ApiPublicHooksFollowupTickRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
  ApiWhatsappTemplatesListRoute: typeof ApiWhatsappTemplatesListRoute
  ApiWhatsappTemplatesSyncRoute: typeof ApiWhatsappTemplatesSyncRoute
  ApiWhatsappTemplatesUpdateRoute: typeof ApiWhatsappTemplatesUpdateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whatsapp': {
      id: '/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof WhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orcamentos': {
      id: '/orcamentos'
      path: '/orcamentos'
      fullPath: '/orcamentos'
      preLoaderRoute: typeof OrcamentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia': {
      id: '/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof IaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/': {
      id: '/campanhas/'
      path: '/campanhas'
      fullPath: '/campanhas/'
      preLoaderRoute: typeof CampanhasIndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/': {
      id: '/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof InboxIndexRouteImport
      parentRoute: typeof InboxRoute
    }
    '/campanhas/nova': {
      id: '/campanhas/nova'
      path: '/campanhas/nova'
      fullPath: '/campanhas/nova'
      preLoaderRoute: typeof CampanhasNovaLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campanhas/$id': {
      id: '/campanhas/$id'
      path: '/campanhas/$id'
      fullPath: '/campanhas/$id'
      preLoaderRoute: typeof CampanhasIdLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/whatsapp': {
      id: '/onboarding/whatsapp'
      path: '/onboarding/whatsapp'
      fullPath: '/onboarding/whatsapp'
      preLoaderRoute: typeof OnboardingWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox/$conversationId': {
      id: '/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof InboxConversationIdRouteImport
      parentRoute: typeof InboxRoute
    }
    '/auth/meta/callback': {
      id: '/auth/meta/callback'
      path: '/auth/meta/callback'
      fullPath: '/auth/meta/callback'
      preLoaderRoute: typeof AuthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/unmapped': {
      id: '/api/whatsapp/unmapped'
      path: '/api/whatsapp/unmapped'
      fullPath: '/api/whatsapp/unmapped'
      preLoaderRoute: typeof ApiWhatsappUnmappedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/token-refresh': {
      id: '/api/whatsapp/token-refresh'
      path: '/api/whatsapp/token-refresh'
      fullPath: '/api/whatsapp/token-refresh'
      preLoaderRoute: typeof ApiWhatsappTokenRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/test-send': {
      id: '/api/whatsapp/test-send'
      path: '/api/whatsapp/test-send'
      fullPath: '/api/whatsapp/test-send'
      preLoaderRoute: typeof ApiWhatsappTestSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/send': {
      id: '/api/whatsapp/send'
      path: '/api/whatsapp/send'
      fullPath: '/api/whatsapp/send'
      preLoaderRoute: typeof ApiWhatsappSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/integration': {
      id: '/api/whatsapp/integration'
      path: '/api/whatsapp/integration'
      fullPath: '/api/whatsapp/integration'
      preLoaderRoute: typeof ApiWhatsappIntegrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/debug': {
      id: '/api/whatsapp/debug'
      path: '/api/whatsapp/debug'
      fullPath: '/api/whatsapp/debug'
      preLoaderRoute: typeof ApiWhatsappDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/test-send': {
      id: '/api/onboarding/test-send'
      path: '/api/onboarding/test-send'
      fullPath: '/api/onboarding/test-send'
      preLoaderRoute: typeof ApiOnboardingTestSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/onboarding/meta-save': {
      id: '/api/onboarding/meta-save'
      path: '/api/onboarding/meta-save'
      fullPath: '/api/onboarding/meta-save'
      preLoaderRoute: typeof ApiOnboardingMetaSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/meta/config': {
      id: '/api/meta/config'
      path: '/api/meta/config'
      fullPath: '/api/meta/config'
      preLoaderRoute: typeof ApiMetaConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/test-now': {
      id: '/api/ai/test-now'
      path: '/api/ai/test-now'
      fullPath: '/api/ai/test-now'
      preLoaderRoute: typeof ApiAiTestNowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/suggest-product': {
      id: '/api/ai/suggest-product'
      path: '/api/ai/suggest-product'
      fullPath: '/api/ai/suggest-product'
      preLoaderRoute: typeof ApiAiSuggestProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/suggest': {
      id: '/api/ai/suggest'
      path: '/api/ai/suggest'
      fullPath: '/api/ai/suggest'
      preLoaderRoute: typeof ApiAiSuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/readiness': {
      id: '/api/ai/readiness'
      path: '/api/ai/readiness'
      fullPath: '/api/ai/readiness'
      preLoaderRoute: typeof ApiAiReadinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/propose-knowledge': {
      id: '/api/ai/propose-knowledge'
      path: '/api/ai/propose-knowledge'
      fullPath: '/api/ai/propose-knowledge'
      preLoaderRoute: typeof ApiAiProposeKnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/pilot-toggle': {
      id: '/api/ai/pilot-toggle'
      path: '/api/ai/pilot-toggle'
      fullPath: '/api/ai/pilot-toggle'
      preLoaderRoute: typeof ApiAiPilotToggleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/mark-sent': {
      id: '/api/ai/mark-sent'
      path: '/api/ai/mark-sent'
      fullPath: '/api/ai/mark-sent'
      preLoaderRoute: typeof ApiAiMarkSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/followup-status': {
      id: '/api/ai/followup-status'
      path: '/api/ai/followup-status'
      fullPath: '/api/ai/followup-status'
      preLoaderRoute: typeof ApiAiFollowupStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/followup-reactivate': {
      id: '/api/ai/followup-reactivate'
      path: '/api/ai/followup-reactivate'
      fullPath: '/api/ai/followup-reactivate'
      preLoaderRoute: typeof ApiAiFollowupReactivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/followup-config': {
      id: '/api/ai/followup-config'
      path: '/api/ai/followup-config'
      fullPath: '/api/ai/followup-config'
      preLoaderRoute: typeof ApiAiFollowupConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/analytics': {
      id: '/api/ai/analytics'
      path: '/api/ai/analytics'
      fullPath: '/api/ai/analytics'
      preLoaderRoute: typeof ApiAiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/agent-tick': {
      id: '/api/ai/agent-tick'
      path: '/api/ai/agent-tick'
      fullPath: '/api/ai/agent-tick'
      preLoaderRoute: typeof ApiAiAgentTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai/agent-takeover': {
      id: '/api/ai/agent-takeover'
      path: '/api/ai/agent-takeover'
      fullPath: '/api/ai/agent-takeover'
      preLoaderRoute: typeof ApiAiAgentTakeoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/templates/update': {
      id: '/api/whatsapp/templates/update'
      path: '/api/whatsapp/templates/update'
      fullPath: '/api/whatsapp/templates/update'
      preLoaderRoute: typeof ApiWhatsappTemplatesUpdateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/templates/sync': {
      id: '/api/whatsapp/templates/sync'
      path: '/api/whatsapp/templates/sync'
      fullPath: '/api/whatsapp/templates/sync'
      preLoaderRoute: typeof ApiWhatsappTemplatesSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/whatsapp/templates/list': {
      id: '/api/whatsapp/templates/list'
      path: '/api/whatsapp/templates/list'
      fullPath: '/api/whatsapp/templates/list'
      preLoaderRoute: typeof ApiWhatsappTemplatesListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/followup-tick': {
      id: '/api/public/hooks/followup-tick'
      path: '/api/public/hooks/followup-tick'
      fullPath: '/api/public/hooks/followup-tick'
      preLoaderRoute: typeof ApiPublicHooksFollowupTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-trigger': {
      id: '/api/public/hooks/agent-trigger'
      path: '/api/public/hooks/agent-trigger'
      fullPath: '/api/public/hooks/agent-trigger'
      preLoaderRoute: typeof ApiPublicHooksAgentTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InboxRouteChildren {
  InboxConversationIdRoute: typeof InboxConversationIdRoute
  InboxIndexRoute: typeof InboxIndexRoute
}

const InboxRouteChildren: InboxRouteChildren = {
  InboxConversationIdRoute: InboxConversationIdRoute,
  InboxIndexRoute: InboxIndexRoute,
}

const InboxRouteWithChildren = InboxRoute._addFileChildren(InboxRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  IaRoute: IaRoute,
  InboxRoute: InboxRouteWithChildren,
  LoginRoute: LoginRoute,
  OrcamentosRoute: OrcamentosRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  PrivacyRoute: PrivacyRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WhatsappRoute: WhatsappRoute,
  OnboardingWhatsappRoute: OnboardingWhatsappRoute,
  CampanhasIdLazyRoute: CampanhasIdLazyRoute,
  CampanhasNovaLazyRoute: CampanhasNovaLazyRoute,
  CampanhasIndexLazyRoute: CampanhasIndexLazyRoute,
  ApiAiAgentTakeoverRoute: ApiAiAgentTakeoverRoute,
  ApiAiAgentTickRoute: ApiAiAgentTickRoute,
  ApiAiAnalyticsRoute: ApiAiAnalyticsRoute,
  ApiAiFollowupConfigRoute: ApiAiFollowupConfigRoute,
  ApiAiFollowupReactivateRoute: ApiAiFollowupReactivateRoute,
  ApiAiFollowupStatusRoute: ApiAiFollowupStatusRoute,
  ApiAiMarkSentRoute: ApiAiMarkSentRoute,
  ApiAiPilotToggleRoute: ApiAiPilotToggleRoute,
  ApiAiProposeKnowledgeRoute: ApiAiProposeKnowledgeRoute,
  ApiAiReadinessRoute: ApiAiReadinessRoute,
  ApiAiSuggestRoute: ApiAiSuggestRoute,
  ApiAiSuggestProductRoute: ApiAiSuggestProductRoute,
  ApiAiTestNowRoute: ApiAiTestNowRoute,
  ApiMetaConfigRoute: ApiMetaConfigRoute,
  ApiOnboardingMetaSaveRoute: ApiOnboardingMetaSaveRoute,
  ApiOnboardingTestSendRoute: ApiOnboardingTestSendRoute,
  ApiWhatsappDebugRoute: ApiWhatsappDebugRoute,
  ApiWhatsappIntegrationRoute: ApiWhatsappIntegrationRoute,
  ApiWhatsappSendRoute: ApiWhatsappSendRoute,
  ApiWhatsappTestSendRoute: ApiWhatsappTestSendRoute,
  ApiWhatsappTokenRefreshRoute: ApiWhatsappTokenRefreshRoute,
  ApiWhatsappUnmappedRoute: ApiWhatsappUnmappedRoute,
  AuthMetaCallbackRoute: AuthMetaCallbackRoute,
  ApiPublicHooksAgentTriggerRoute: ApiPublicHooksAgentTriggerRoute,
  ApiPublicHooksFollowupTickRoute: ApiPublicHooksFollowupTickRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
  ApiWhatsappTemplatesListRoute: ApiWhatsappTemplatesListRoute,
  ApiWhatsappTemplatesSyncRoute: ApiWhatsappTemplatesSyncRoute,
  ApiWhatsappTemplatesUpdateRoute: ApiWhatsappTemplatesUpdateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
